# scenario_seed: 1804502687
apiVersion: v1
kind: Pod
metadata:
  name: rq1-s235
  labels:
    rq1-scenario: "s235"
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
      resources:
        requests: {cpu: 50m, memory: 32Mi}
  nodeSelector:
    zone: "a"
