# scenario_seed: 1812140441
apiVersion: v1
kind: Pod
metadata:
  name: rq1-s004
  labels:
    rq1-scenario: "s004"
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
      resources:
        requests: {cpu: 50m, memory: 32Mi}
  nodeSelector:
    role: "general"
