# scenario_seed: 1867302554
apiVersion: v1
kind: Pod
metadata:
  name: rq1-s056
  labels:
    rq1-scenario: "s056"
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
      resources:
        requests: {cpu: 50m, memory: 32Mi}
