# scenario_seed: 1564319318
apiVersion: v1
kind: Pod
metadata:
  name: rq1-s188
  labels:
    rq1-scenario: "s188"
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
      resources:
        requests: {cpu: 50m, memory: 32Mi}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: rack
              operator: In
              values: ["r2"]
